# Generated by Django 5.0.3 on 2024-09-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_curso_codigo_alter_estudante_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='celular',
            field=models.CharField(max_length=15),
        ),
    ]
